version: '3.1'

services:
  # golang:
  #   build: .
  #   restart: always
  #   ports:
  #     - 8090:8090 

  postgres:
    build: ./db
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
    # volumes:
      # - ./db/base:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 6900:8080